pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // JitPack repository for llama.cpp and other GitHub libraries
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "EgyptianAgent"
include ':app'